### ISSUE TITLE
Can not install using pip

### ISSUE THREAD

**Issue by matteoipri** [yuvipanda/jupyterhub-dummy-authenticator#1]
Hi, I've been trying to install this authenticator inside a docker image to test jupyterhub with dockerspawner.
I can install dockerspawner, but I can not install this dummy authenticator.
I get the following error, even when I try to install the authenticator on my PC running OS X 10.10.5.

```
$ pip install jupyterhub-dummyauthenticator
Collecting jupyterhub-dummyauthenticator
  Could not find a version that satisfies the requirement jupyterhub-dummyauthenticator (from versions: )
No matching distribution found for jupyterhub-dummyauthenticator
```

How can I solve this?
In the meantime I found a workaround for docker: I copy the class definition in the `jupyterhub_config.py` file.
Thanks,
Matteo

**Comment by benhosmer** [comment]
The package doesn't exist in pypi, so pip won't find it. You _can_ still use pip by pointing to the zip file:

`$ pip install https://github.com/yuvipanda/jupyterhub-dummy-authenticator/archive/master.zip`

@yuvipanda needs to add it to pypi and then you could install it.

**Comment by yuvipanda** [comment]
Hello! Sorry about that! I've published it at https://pypi.python.org/pypi?:action=display&name=jupyterhub-dummyauthenticator&version=0.1 now!
